/**
 * Client-side fallback preset list — mirrors backend /app/backend/presets.py.
 * Used when /api/presets fails (e.g., deployed app temporarily can't reach backend,
 * CORS hiccup, cold-start 502, etc.) so the 8 signature presets always render.
 */
export const FALLBACK_PRESETS = [
  {
    id: "universal",
    name: "Universal",
    color: "#3B82F6",
    icon: "Globe",
    genres: ["Rock", "Pop", "Electronic", "Alternative"],
    description: "Natural dynamic and tonal balancing.",
    lufs: -14,
    targets: ["streaming", "youtube"],
  },
  {
    id: "fire",
    name: "Fire",
    color: "#EF4444",
    icon: "Flame",
    genres: ["Trap", "Experimental", "Reggaeton"],
    description: "Punchy lows and midrange clarity.",
    lufs: -9,
    targets: ["mastering"],
  },
  {
    id: "clarity",
    name: "Clarity",
    color: "#06B6D4",
    icon: "Sparkles",
    genres: ["Classical", "R&B", "Singer-songwriter"],
    description: "Pristine highs with light dynamic expansion.",
    lufs: -16,
    targets: ["apple_music"],
  },
  {
    id: "tape",
    name: "Tape",
    color: "#F59E0B",
    icon: "Radio",
    genres: ["Jazz", "Alternative", "Indie", "Rock"],
    description: "Warm saturation with analog dynamics.",
    lufs: -13,
    targets: ["youtube", "mastering"],
  },
  {
    id: "natural",
    name: "Natural",
    color: "#10B981",
    icon: "Leaf",
    genres: ["Acoustic", "Jazz", "Singer-songwriter"],
    description: "Balanced dynamics and gentle compression.",
    lufs: -16,
    targets: ["apple_music", "broadcast"],
  },
  {
    id: "spatial",
    name: "Spatial",
    color: "#8B5CF6",
    icon: "Orbit",
    genres: ["Ambient", "Experimental", "Electronic"],
    description: "Atmospheric reverb and enhanced stereo width.",
    lufs: -14,
    targets: ["streaming", "youtube"],
  },
  {
    id: "cinematic",
    name: "Cinematic",
    color: "#EAB308",
    icon: "Film",
    genres: ["Soundtrack", "Orchestral", "Classical"],
    description: "Intense saturation and harmonic distortion.",
    lufs: -12,
    targets: ["mastering"],
  },
  {
    id: "punch",
    name: "Punch",
    color: "#EC4899",
    icon: "Zap",
    genres: ["Hip Hop", "Trap", "R&B"],
    description: "Energetic bass combined with boosted highs.",
    lufs: -10,
    targets: ["mastering"],
  },
];
